// packages/example-app-angular/src/app/app.component.ts
import { Component, ChangeDetectorRef, OnInit, OnDestroy } from '@angular/core';
import { RouterOutlet, RouterLink, ActivatedRoute, Router } from '@angular/router';
import { ReactWrapperComponent } from './react-wrapper.component';
import { CommonModule } from '@angular/common';
import 'postal';
const postal = (window as any).postal;

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, CommonModule],
  template: `
    <div style="padding: 20px; font-family: sans-serif;">
      <nav style="margin-bottom: 20px; padding-bottom: 10px; border-bottom: 1px solid #ccc;">
        <h2>Dynamic Form Sandbox (Angular Host)</h2>
        <div style="display: flex; gap: 10px;">
          <a routerLink="/person/list">Persons (REST)</a>
          <a routerLink="/candy/list">Candies (REST)</a>
          <a routerLink="/store/list">Stores (GraphQL)</a>
        </div>
      </nav>

      <router-outlet></router-outlet>
    </div>
  `
})
export class AppComponent {}

@Component({
  selector: 'app-entity-list',
  standalone: true,
  imports: [ReactWrapperComponent],
  template: `
    <app-react-wrapper
      url="http://localhost:5001/assets/remoteEntry.js"
      scope="dynamic_form"
      module="./EntityList"
      [componentProps]="props"
    ></app-react-wrapper>
  `
})
export class EntityListComponent implements OnInit, OnDestroy {
  entity = '';
  private subs: any[] = [];

  get props() {
    return {
      entity: this.entity
    };
  }

  constructor(private route: ActivatedRoute, private router: Router, private cdr: ChangeDetectorRef) {
    this.route.params.subscribe(params => {
      this.entity = params['entity'];

      (postal as any).publish({
        channel: 'dynamic_form',
        topic: 'entity.loadList',
        data: { entity: this.entity }
      });

      this.cdr.detectChanges();
    });
  }

  ngOnInit() {
    this.subs.push(
      (postal as any).subscribe({
        channel: 'dynamic_form',
        topic: 'entity.ready',
        callback: (data: any) => {
          if (data.type === 'list') {
            (postal as any).publish({
              channel: 'dynamic_form',
              topic: 'entity.loadList',
              data: { entity: this.entity }
            });
          }
        }
      })
    );

    this.subs.push(
      (postal as any).subscribe({
        channel: 'dynamic_form',
        topic: 'entity.create',
        callback: (data: any) => {
          if (data.entity === this.entity) {
            this.router.navigate([`/${this.entity}/form`]);
          }
        }
      })
    );
    this.subs.push(
      (postal as any).subscribe({
        channel: 'dynamic_form',
        topic: 'entity.edit',
        callback: (data: any) => {
          if (data.entity === this.entity) {
            this.router.navigate([`/${this.entity}/form/${data.id}`]);
          }
        }
      })
    );
  }

  ngOnDestroy() {
    this.subs.forEach(sub => sub.unsubscribe());
  }
}

@Component({
  selector: 'app-entity-form',
  standalone: true,
  imports: [ReactWrapperComponent],
  template: `
    <app-react-wrapper
      url="http://localhost:5001/assets/remoteEntry.js"
      scope="dynamic_form"
      module="./EntityForm"
      [componentProps]="props"
    ></app-react-wrapper>
  `
})
export class EntityFormComponent implements OnInit, OnDestroy {
  entity = '';
  id?: string;
  private subs: any[] = [];

  get props() {
    return {
      entity: this.entity,
      id: this.id
    };
  }

  constructor(private route: ActivatedRoute, private router: Router, private cdr: ChangeDetectorRef) {
    this.route.params.subscribe(params => {
      this.entity = params['entity'];
      this.id = params['id'];

      (postal as any).publish({
        channel: 'dynamic_form',
        topic: 'entity.loadForm',
        data: { entity: this.entity, id: this.id }
      });

      this.cdr.detectChanges();
    });
  }

  ngOnInit() {
    this.subs.push(
      (postal as any).subscribe({
        channel: 'dynamic_form',
        topic: 'entity.ready',
        callback: (data: any) => {
          if (data.type === 'form') {
            (postal as any).publish({
              channel: 'dynamic_form',
              topic: 'entity.loadForm',
              data: { entity: this.entity, id: this.id }
            });
          }
        }
      })
    );

    this.subs.push(
      (postal as any).subscribe({
        channel: 'dynamic_form',
        topic: 'entity.saved',
        callback: (data: any) => {
          if (data.entity === this.entity) {
            alert('Saved successfully!');
            this.router.navigate([`/${this.entity}/list`]);
          }
        }
      })
    );
    this.subs.push(
      (postal as any).subscribe({
        channel: 'dynamic_form',
        topic: 'entity.error',
        callback: (data: any) => {
          if (data.entity === this.entity) {
            alert('An error occurred while saving.');
            console.error(data.error);
          }
        }
      })
    );
    this.subs.push(
      (postal as any).subscribe({
        channel: 'dynamic_form',
        topic: 'entity.cancel',
        callback: (data: any) => {
          if (data.entity === this.entity) {
            this.router.navigate([`/${this.entity}/list`]);
          }
        }
      })
    );
  }

  ngOnDestroy() {
    this.subs.forEach(sub => sub.unsubscribe());
  }
}

// packages/microfrontends/src/App.tsx
import { useEffect } from 'react';
import { BrowserRouter, Routes, Route, Link, useParams, useNavigate } from 'react-router-dom';
import * as _postal from 'postal';
const postal = _postal as any;
import EntityList from './components/EntityList';
import EntityForm from './components/EntityForm';

function ListWrapper() {
  const { entity } = useParams<{ entity: string }>();
  const navigate = useNavigate();

  useEffect(() => {
    const subCreate = postal.subscribe({
      channel: 'dynamic_form',
      topic: 'entity.create',
      callback: (data: any) => {
        if (data.entity === entity) {
          navigate(`/${entity}/form`);
        }
      }
    });

    const subEdit = postal.subscribe({
      channel: 'dynamic_form',
      topic: 'entity.edit',
      callback: (data: any) => {
        if (data.entity === entity) {
          navigate(`/${entity}/form/${data.id}`);
        }
      }
    });

    return () => {
      subCreate.unsubscribe();
      subEdit.unsubscribe();
    };
  }, [entity, navigate]);

  useEffect(() => {
    if (!entity) return;
    const subReady = postal.subscribe({
      channel: 'dynamic_form',
      topic: 'entity.ready',
      callback: (data: any) => {
        if (data.type === 'list') {
          postal.publish({
            channel: 'dynamic_form',
            topic: 'entity.loadList',
            data: { entity }
          });
        }
      }
    });

    postal.publish({
      channel: 'dynamic_form',
      topic: 'entity.loadList',
      data: { entity }
    });

    return () => {
      subReady.unsubscribe();
    };
  }, [entity]);

  if (!entity) return <p>No entity selected</p>;

  return <EntityList />;
}

function FormWrapper() {
  const { entity, id } = useParams<{ entity: string, id?: string }>();
  const navigate = useNavigate();

  useEffect(() => {
    const subSaved = postal.subscribe({
      channel: 'dynamic_form',
      topic: 'entity.saved',
      callback: (data: any) => {
        if (data.entity === entity) {
          navigate(`/${entity}/list`);
        }
      }
    });

    const subError = postal.subscribe({
      channel: 'dynamic_form',
      topic: 'entity.error',
      callback: (data: any) => {
        if (data.entity === entity) {
          console.error(data.error);
        }
      }
    });

    const subCancel = postal.subscribe({
      channel: 'dynamic_form',
      topic: 'entity.cancel',
      callback: (data: any) => {
        if (data.entity === entity) {
          navigate(`/${entity}/list`);
        }
      }
    });

    return () => {
      subSaved.unsubscribe();
      subError.unsubscribe();
      subCancel.unsubscribe();
    };
  }, [entity, navigate]);

  useEffect(() => {
    if (!entity) return;
    const subReady = postal.subscribe({
      channel: 'dynamic_form',
      topic: 'entity.ready',
      callback: (data: any) => {
        if (data.type === 'form') {
          postal.publish({
            channel: 'dynamic_form',
            topic: 'entity.loadForm',
            data: { entity, id }
          });
        }
      }
    });

    postal.publish({
      channel: 'dynamic_form',
      topic: 'entity.loadForm',
      data: { entity, id }
    });

    return () => {
      subReady.unsubscribe();
    };
  }, [entity, id]);

  if (!entity) return <p>No entity selected</p>;

  return <EntityForm />;
}

function App() {
  return (
    <BrowserRouter>
      <div style={{ padding: '20px', fontFamily: 'sans-serif' }}>
        <nav style={{ marginBottom: '20px', paddingBottom: '10px', borderBottom: '1px solid #ccc' }}>
          <h2>Dynamic Form Sandbox</h2>
          <div style={{ display: 'flex', gap: '10px' }}>
            <Link to="/person/list">Persons (REST)</Link>
            <Link to="/candy/list">Candies (REST)</Link>
            <Link to="/store/list">Stores (GraphQL)</Link>
          </div>
        </nav>

        <Routes>
          <Route path="/:entity/list" element={<ListWrapper />} />
          <Route path="/:entity/form/:id?" element={<FormWrapper />} />
          <Route path="/" element={<p>Select an entity above to manage.</p>} />
        </Routes>
      </div>
    </BrowserRouter>
  );
}

export default App;
